version: '3.8'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    container_name: esmaster1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: "no"
    environment:
      - node.name=esmaster1
      - cluster.initial_master_nodes=esmaster1,esmaster2,esmaster3
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1  
    networks:
      - esnet

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    container_name: esmaster2
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    ports:
      - 9201:9201
    restart: "no"
    environment:
      - node.name=esmaster2
      - discovery.seed_hosts=esmaster1
      - cluster.initial_master_nodes=esmaster1,esmaster2,esmaster3
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1  
    networks:
      - esnet

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    container_name: esmaster3
    volumes:
      - esdata03:/usr/share/elasticsearch/data
    ports:
      - 9202:9202
    restart: "no"
    environment:
      - node.name=esmaster3
      - discovery.seed_hosts=esmaster1
      - cluster.initial_master_nodes=esmaster1,esmaster2,esmaster3
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1  
    networks:
      - esnet

  kibana:
    depends_on:
      - es01
      - es02
      - es03
    image: docker.elastic.co/kibana/kibana:8.4.0
    container_name: kibana
    volumes:
      - kibana-cluster:/usr/share/kibana/data
    ports:
     - 5601:5601
    restart: "no"
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    networks:
      - esnet

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
  kibana-cluster:
    driver: local

networks:
  esnet:
